### ISSUE TITLE
設定画面の実装

### ISSUE THREAD

**Issue by sinokuma** [epotech/JenarMine#11]
- 設定画面の実装  
  使用ユーザ単位で設定できる画面を実装する。
- 実装の方針  
  設定項目については検討し、イテレートする中で適宜追加する。
  共通の方針として、HTML5のローカルストレージ（Web Storage）に情報を格納する。
- タスク一覧  
  - [x] WebStorage調査
    - [x] 格納可能な容量→おそらく10MB
    - [x] パフォーマンス→I/Oにかかるコストはあるが、テキストの設定データ程度であれば問題なし
  - [x] 実装機能検討（開発を進める中で適宜リストを追加）
    - [x] 接続先URL変更機能（Jenkins、Sonar、Redmineそれぞれ個別に設定できるとよい？）
    - [x] ログイン情報設定・自動ログイン機能
    - [x] 利用サービスの選択（Redmine/Jenkins/Sonarすべてを利用する前提としないため）
    - [x] Redmineは必ず利用する前提なので、RedmineのみOFFにできないようにする
    - [x] localStorageへの設定情報格納
    - [x] 起動時にlocalStorageから設定情報をロードする機能
    - [x] 初回起動時は利用サービスが全てOFFのはず。その場合設定画面に遷移するようにしたい。（スプラッシュも出したい！）
  - [x] 変更可能としたい設定項目の洗い出し
    - [x] jenkins - 表示するjob名(複数)
    - [x] jenkins - ApiKey
    - [x] Redmineチケット通知間隔設定機能(単位は時間）
    - [x] Redmine - ApiKey
    - [x] Sonar - TOPページに表示するプロジェクトID
  - [x] 設定変更があれば全ての機能に変更を通知して反映したい（イベント通知で実現ができないか検討）
  - [x] お気に入りジョブは削除機能を実装したい
  - [x] ログインURLを指定する際に末尾「/」がついていても対応できるようにする
  - [x] スクロールバーを丸みを帯びさせる
  - [x] Redmineの通知間隔は時間にするようプレースホルダーを修正

**Comment by TakuyaMatsuoka** [comment]
ログインはRedmineのみを一旦の対象とする。

**Comment by TakuyaMatsuoka** [comment]
jenkins - 実行時のパラメータ(複数)については今後の機能拡張で別途検討する。

**Comment by TakuyaMatsuoka** [comment]
RedmineのURLは「/login」が無いものを設定される前提として、自動ログインをする際には指定されたURL + 「/login」にアクセスした上でログイン処理を行うこととする。
