### ISSUE TITLE
機能集約（Sonar）

### ISSUE THREAD

**Issue by TakuyaMatsuoka** [epotech/JenarMine#13]
機能
Redmine下部に、Sonarダッシュボードを表示する。

タスク

事前準備
- [x] Sonar API調査(Wikiにまとめる)
- [x] 機能完成イメージ擦り合わせ
  - [x] 表示項目決定

実装
- [x] メトリクスデータ取得（csvやjsonが多い）
- [x] メトリクスデータ表示（csvやjsonが多いので、c3.jsまたはd3.jsとの親和性あり？）
- [x] APIパラメータ設定（LocalStrage使う？）
- [x] Sonar表示用パネルの表示サイズ切り替え（ぬるりと動くぜ！）

**Comment by sinokuma** [comment]
全タスク対応完了のため、クローズ
