### ISSUE TITLE
Jenkins,Sonarに関しては利用フラグがたっていない場合はWeb APIを実行しないようにしたい

### ISSUE THREAD

**Issue by TakuyaMatsuoka** [epotech/JenarMine#17]
Jenkins,Sonarに関しては利用フラグがたっていない場合はWeb APIを実行しないようにしたい。
また、アクセス先に不正なURLを指定されている場合も同様に実行しないようにしたい。

**Comment by sinokuma** [comment]
利用フラグなしの場合に、WebAPIを実行させずに、最小化する対応をしました。
不正URL対応は、別途します。
